version: "3.8"
services:
    app:
        build: .
        volumes:
            - .:/django
        ports:
            - 8000:8000
        image: app:django
        container_name: django_container
        command: python django/manage.py runserver 0.0.0.0:8000
        depends_on:
            - migration
            - pg

    migration:
        image: app:django
        command: python django/manage.py migrate
        depends_on:
            - pg

    filltable:
        image: postgres:14.1-alpine3.15
        environment:
            POSTGRES_USER: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
            PGUSER: postgres
        volumes: 
            - ./fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
        depends_on:
            - app
            - pg
            - migration
            
    pg:
        container_name: pg_container
        image: postgres:14.1-alpine3.15
        restart: always
        environment:
            POSTGRES_DB: dwstore
            POSTGRES_USER: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
            PGUSER: postgres
        ports:
        - "5432:5432"

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:6.4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin123
            PGADMIN_LISTEN_PORT: 5433
            PGADMIN_CONFIG_SERVER_MODE: "False"
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
            PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
        ports:
        - "5433:5433"
        depends_on:
        - pg
