# Generated by Django 4.1.2 on 2022-10-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontstore', '0002_rename_po_id_purchaseinvoices_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaseinvoices',
            name='purchase_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='po_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saleinvoices',
            name='invoice_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saleorders',
            name='order_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
